### ISSUE TITLE
PHP error on Sign in/ Registration page

### ISSUE THREAD

**Issue by rbass314** [newtribesmission/NTM-WPMem-Email-As-Username#2]
I get this error at the top of the Sign in/ Registration form on a blocked page:

Warning: Missing argument 2 for ntmeau_e2u_wpmem_reg_form() in /home2/klr/public_html/retrieverbarking/wp-content/plugins/email-as-username-for-wp-members/email-as-username-for-wp-members.php on line 100

**Comment by jrseabio** [comment]
Same here.  Any quick fix suggestions?

**Comment by stevish-com** [comment]
I will look into this soon. Best bet is to probably make that second
parameter optional...

**Comment by stevish-com** [comment]
I've made a change that should fix this, but I'm unable to test it now. If you guys are able, could you download the bleeding edge version to test it out? Only one line was changed, so there's very little chance anything went wrong. Just want to see if it fixed the problem before I push the update to the plugin repository

**Comment by jrseabio** [comment]
Hi Stephen,

I commented on your bleeding edge post, but wanted to send you a personal “thank you” as well.  I appreaciate your quick response time and expertise in delivering a solid solution to our request.  If only every other developer were as “on it” as you have been, the world would be a much different place!

Thanks again!

John R. Richards, II

Managing Member

616.617.4922

 http://www.alevelgroup.com/      http://www.linkedin.com/in/jrrichardsii/ 

This email and any attachments contain confidential information intended only for the use of the individual or entity to which they are addressed.  If you received this communication in error, you are hereby notified than any dissemination, distribution or copying is strictly prohibited.  Please notify us of the error immediately by return email and delete this message and any attachment from your system.
